### ISSUE TITLE
Images are in torch.cuda.DoubleTensor while the weights are in torch.cuda.FloatTensor.

### ISSUE THREAD

**Issue by Hemant-Parihar** [kdexd/probnmn-clevr#1]
I followed all the steps as mentioned in the document but While running the command for Phase: module_training.

> python scripts/train.py \
>     --config-yml configs/module_training.yml \
>     --phase module_training \
>     --config-override CHECKPOINTS.QUESTION_CODING checkpoints/question_coding_ours/question_coding_best.pth \
>     --gpu-ids 0 1 2 3 \
>     --serialization-dir checkpoints/module_training

I'm getting this error: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

on line: output_dict = self._nmn(batch["image"], pg_output_dict["predictions"], batch["answer"]) in module_training_trainer.py

When I change the type of batch["image"] to batch["image"].float() i got error: TypeError: zip argument #1 must support iteration

I tried different ways to convert batch["image"] of type torch.cuda.FloatTensor but every time i got it is not iterable. I also tried to change the get_item from dataset to return an image of type float but still, it is not working.

I am pasting the completing error for clear reference.

```
Batch['image'] type : torch.cuda.DoubleTensor

> Traceback (most recent call last):
>   File "scripts/train.py", line 138, in <module>
>     trainer.step(iteration)
>   File "/data/vivek/neural-symbolic/probnmn-clevr/probnmn/trainers/_trainer.py", line 147, in step
>     output_dict = self._do_iteration(batch)
>   File "/data/vivek/neural-symbolic/probnmn-clevr/probnmn/trainers/module_training_trainer.py", line 96, in _do_iteration
>     output_dict = self._nmn(batch["image"], pg_output_dict["predictions"], batch["answer"])
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
>     outputs = self.parallel_apply(replicas, inputs, kwargs)
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
>     return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
>     raise output
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
>     output = module(*input, **kwargs)
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/vivek/neural-symbolic/probnmn-clevr/probnmn/models/nmn.py", line 183, in forward
>     feat_input_volume = self.stem(features)
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
>     input = module(input)
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/vivek/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same
> 
> 
```

**Comment by ginxy** [comment]
Hi

I had the same problem. The solution, at least the one I have found, is to cast the tensor for the input data to a double type. I've done that by simply adding .double() to the script "extract_features.py" for the class ClevrImagesDataset(Dataset) which loads, transforms and returns a tensor for feature extraction. The function __getitem__ will look like this: 

    def __getitem__(self, index):
        image = Image.open(self._image_paths[index]).convert("RGB")
        image_tensor = self._transform(image)
        return image_tensor.double()

This should get rid of the dtype issue.

**Comment by Hemant-Parihar** [comment]
Hi
I still got the same error. When I changed the ClevrImagesDataset(Dataset) class in extract_features.py.

`Traceback (most recent call last):
  File "scripts/preprocess/extract_features.py", line 142, in <module>
    main(args)
  File "scripts/preprocess/extract_features.py", line 129, in main
    output_features = feature_extractor(batch)
  File "/home/badri/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/badri/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/badri/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/badri/anaconda3/envs/probnmn/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same`

**Comment by kdexd** [comment]
Please pull from latest master, this issue should be fixed. Feel free to re-open!
